# Generated by Django 4.0.1 on 2022-03-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='test',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
