# Generated by Django 4.0.1 on 2022-03-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_choice_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
