# Generated by Django 4.0.1 on 2022-01-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='bet', unique=True),
            preserve_default=False,
        ),
    ]
