# Generated by Django 4.0.1 on 2022-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='test2', unique=True),
            preserve_default=False,
        ),
    ]
