# Generated by Django 4.0.1 on 2022-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='s', unique=True),
            preserve_default=False,
        ),
    ]
