# Generated by Django 4.0.1 on 2022-01-21 00:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='user', unique=True),
        ),
    ]
