# Generated by Django 4.0.1 on 2022-02-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_questionanswer_level'),
        ('userprofile', '0007_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(to='learning.Course'),
        ),
    ]
