# Generated by Django 4.0.1 on 2022-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_questionanswer_level'),
        ('userprofile', '0008_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(blank=True, to='learning.Course'),
        ),
    ]
