# Generated by Django 4.0.1 on 2022-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_level'),
        ('userprofile', '0009_alter_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='learning.Level'),
        ),
    ]
