# Generated by Django 4.0.1 on 2022-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_profile_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='test@gmail.cmom', max_length=100),
            preserve_default=False,
        ),
    ]
