# Generated by Django 4.0.1 on 2022-05-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_questionanswer_answer_and_more'),
        ('userprofile', '0012_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentCourse', to='learning.course'),
        ),
    ]
