# Generated by Django 4.0.1 on 2022-01-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(default='spanish', max_length=255),
        ),
    ]
