# Generated by Django 4.0.1 on 2022-01-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='language',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='language',
        ),
    ]
