# Generated by Django 4.0.1 on 2022-02-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_guide_language_remove_lesson_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
