# Generated by Django 4.0.1 on 2022-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_questionanswer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='questionKeyword',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
