# Generated by Django 4.0.1 on 2022-01-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
    ]
