# Generated by Django 4.0.1 on 2022-02-23 00:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_questionanswer_questionkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='richContent',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
