# Generated by Django 4.0.1 on 2022-02-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_lesson_richcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='content', null=True),
        ),
    ]
