# Generated by Django 4.0.1 on 2022-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='questionKeyword',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
