# Generated by Django 4.0.1 on 2022-03-06 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_questionanswer_questionkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.lesson'),
        ),
    ]
