# Generated by Django 4.0.1 on 2022-03-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_questionanswer_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='numLevels',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
