# Generated by Django 4.0.1 on 2022-01-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_lesson_orderingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default='caption', max_length=255),
            preserve_default=False,
        ),
    ]
