# Generated by Django 4.0.1 on 2022-01-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
