# Generated by Django 4.0.1 on 2022-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
