# Generated by Django 4.0.1 on 2022-01-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_course_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
    ]
