# Generated by Django 4.0.1 on 2022-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_guide_richcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.CharField(max_length=600),
        ),
    ]
