# Generated by Django 4.0.1 on 2022-01-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_remove_course_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='orderingID',
            field=models.IntegerField(),
        ),
    ]
