# Generated by Django 4.0.1 on 2022-01-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_lesson_orderingid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
