# Generated by Django 4.0.1 on 2022-01-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
