# Generated by Django 4.0.1 on 2022-01-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
