# Generated by Django 4.0.1 on 2022-01-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_guide_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='content'),
        ),
    ]
